modelo Room
los-devfs/cine-backend pull request #24
Opened 2022-08-23 03:06 UTC by Remp31

2022-08-23 23:53 UTC, servo98 requested changes

2022-08-23 23:53 UTC, servo98 commented on api/model/Room.js
> +const userSchema = new mongoose.Schema({
cambiar nombre de constante

2022-08-23 23:53 UTC, servo98 commented on api/model/Room.js
> +    room_number : {
usar camel case

2022-08-23 23:53 UTC, servo98 commented on api/model/Room.js
> +    seat: {
que no haya asientos negativos min 1

2022-08-24 00:03 UTC, closed without merging

2022-08-24 00:03 UTC, Remp31 commented
Crearé otro pullRequest