consultar peliculas
los-devfs/cine-backend pull request #32
Opened 2022-08-24 00:31 UTC by benildacoari

2022-08-24 00:47 UTC, servo98 requested changes
falta archivo movieRoutes.js

2022-08-24 01:02 UTC, benildacoari commented
@servo98  ya agregue el archivo que faltaba

2022-08-24 01:07 UTC, servo98 commented on api/controllers/movieController.js
> +        const movies = await Movie.find();
Falta que el cliente pueda filtar las películas

2022-08-24 23:56 UTC, servo98 submitted a review, later dismissed

2022-08-25 00:10 UTC, servo98 approved these changes

2022-08-25 00:10 UTC, merged