Feat/eu 36/middleware rol
los-devfs/cine-backend pull request #41
Opened 2022-08-24 02:24 UTC by kitoyjami

Se creo el archivo roleValidator.js y se hizo el middleware para validacion de rol

2022-08-24 02:34 UTC, servo98 requested changes

2022-08-24 02:34 UTC, servo98 commented on api/middlewares/roleValidator.js
> +        const result = req.roles.map(
solo usar el include de req.role

2022-08-24 02:34 UTC, servo98 commented on api/middlewares/roleValidator.js
> +        if (!result)
meter el resultado del include en el if

2022-08-25 03:48 UTC, kitoyjami commented on api/middlewares/roleValidator.js
> +        const result = req.roles.map(
se reviso y se uso solo req.role

2022-08-25 03:48 UTC, kitoyjami commented on api/middlewares/roleValidator.js
> +        if (!result)
include dentro del if

2022-08-25 23:44 UTC, servo98 approved these changes

2022-08-25 23:45 UTC, merged